#!/usr/bin/env bash 

comparaison="0" 


if [ $1 -gt $2 ]
then
comparaison=$1
else
comparaison=$2
fi 


if [ $comparaison -gt $3 ]
then
echo "$comparaison est le plus grand"
else
echo "$3 est trop balèze"
fi
